package codegen

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"text/template"
)

// ManifestEmitter renders connector/manifest.toml from the overlay's
// connector + credential + network blocks. Skipped silently when the
// overlay doesn't carry enough to render a runnable manifest — see
// shouldEmitManifest below — so existing test cases that only configure
// actions stay unchanged.
//
// The `0.0.0-dev` and `sha256:bound-at-release` placeholders the
// action.md emitter follows apply here too; the release workflow
// substitutes them per ADR-0002.
type ManifestEmitter struct{}

// Emit writes connector/manifest.toml under outDir. No-op if the overlay
// doesn't declare credential.kind + network.hosts + connector.name +
// connector.publisher.
func (ManifestEmitter) Emit(_ Spec, overlay Overlay, outDir string) error {
	if !shouldEmitManifest(overlay) {
		return nil
	}
	view := buildManifestView(overlay)
	dir := filepath.Join(outDir, "connector")
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return err
	}
	f, err := os.Create(filepath.Join(dir, "manifest.toml"))
	if err != nil {
		return err
	}
	defer f.Close()
	return manifestTmpl.Execute(f, view)
}

// shouldEmitManifest is the gate: every connector that wants a generated
// manifest declares at least these four fields. The Google connector
// uses a hand-written manifest until it migrates; this gate keeps codegen
// out of its way.
func shouldEmitManifest(o Overlay) bool {
	c := o.Connector
	return c.Name != "" &&
		c.Publisher != "" &&
		c.Credential.Kind != "" &&
		len(c.Network.Hosts) > 0
}

// manifestView is the template input. Credential rendering branches on
// Kind, so the template uses a discriminator helper rather than embedding
// kind-specific fields directly.
type manifestView struct {
	Name        string
	Publisher   string
	Hosts       []string
	Credential  credentialView
	OAuth2Block *oauth2View
}

type credentialView struct {
	Kind   string
	Header string // api_key kind only — empty omits the line
	Format string // api_key kind only — empty omits the line
}

type oauth2View struct {
	AuthorizeURL string
	TokenURL     string
	ClientID     string
	Scopes       []string
}

func buildManifestView(o Overlay) manifestView {
	c := o.Connector
	view := manifestView{
		Name:      c.Name,
		Publisher: c.Publisher,
		Hosts:     append([]string(nil), c.Network.Hosts...),
		Credential: credentialView{
			Kind: c.Credential.Kind,
		},
	}
	switch c.Credential.Kind {
	case "api_key":
		view.Credential.Header = credentialHeaderOrDefault(c.Credential.Header)
		view.Credential.Format = credentialFormatOrDefault(c.Credential.Format)
	case "oauth2":
		view.OAuth2Block = &oauth2View{
			AuthorizeURL: c.Credential.AuthorizeURL,
			TokenURL:     c.Credential.TokenURL,
			ClientID:     c.Credential.ClientID,
			Scopes:       append([]string(nil), c.Credential.Scopes...),
		}
	}
	return view
}

// credentialHeaderOrDefault returns the overlay value when set, otherwise
// the runtime's current convention. Matches the proposed default in
// aileron#917 so the emitted manifest is correct both before and after
// that issue lands.
func credentialHeaderOrDefault(s string) string {
	if s == "" {
		return "Authorization"
	}
	return s
}

func credentialFormatOrDefault(s string) string {
	if s == "" {
		return "Bearer {key}"
	}
	return s
}

var manifestTmpl = template.Must(template.New("manifest").Funcs(template.FuncMap{
	"quote":      tomlQuote,
	"quoteList":  tomlStringList,
	"hostsBlock": tomlMultilineList,
}).Parse(manifestTemplate))

const manifestTemplate = `# Aileron connector manifest for {{.Name}}.
#
# Generated by aileron-codegen. The 0.0.0-dev / bound-at-release strings
# are load-bearing placeholders per ADR-0002; the release workflow
# substitutes them at tag time. Do not edit by hand — re-run
# ` + "`task generate`" + ` to refresh.

[connector]
name = {{quote .Name}}
version = "0.0.0-dev"
publisher = {{quote .Publisher}}

[capabilities.network]
hosts = {{hostsBlock .Hosts}}

[capabilities.credential]
kind = {{quote .Credential.Kind}}
{{- if eq .Credential.Kind "api_key"}}
header = {{quote .Credential.Header}}
format = {{quote .Credential.Format}}
{{- end}}
{{- if .OAuth2Block}}

[capabilities.credential.oauth2]
authorize_url = {{quote .OAuth2Block.AuthorizeURL}}
token_url     = {{quote .OAuth2Block.TokenURL}}
client_id     = {{quote .OAuth2Block.ClientID}}
client_secret = "bound-at-release"
scopes = {{hostsBlock .OAuth2Block.Scopes}}
{{- end}}
`

// tomlMultilineList renders a TOML array on multiple lines for
// readability — matches the existing aileron-connector-google manifest
// shape so the diff against hand-written manifests is minimal when a
// connector migrates to codegen.
func tomlMultilineList(items []string) string {
	if len(items) == 0 {
		return "[]"
	}
	var b strings.Builder
	b.WriteString("[\n")
	for _, s := range items {
		fmt.Fprintf(&b, "  %s,\n", tomlQuote(s))
	}
	b.WriteString("]")
	return b.String()
}
