package codegen

import (
	"os"
	"path/filepath"
	"sort"
	"text/template"
)

// SuiteEmitter renders suite.toml at the repo root from the overlay's
// Suite block plus the same operation-filter ActionEmitter uses, so the
// suite stays in sync by construction. No-op when overlay.Suite is nil.
type SuiteEmitter struct{}

func (SuiteEmitter) Emit(spec Spec, overlay Overlay, outDir string) error {
	if overlay.Suite == nil || overlay.Suite.Name == "" {
		return nil
	}
	view := suiteView{
		Name:        overlay.Suite.Name,
		Description: overlay.Suite.Description,
		Actions:     emittedActionSubpaths(spec, overlay),
	}
	f, err := os.Create(filepath.Join(outDir, "suite.toml"))
	if err != nil {
		return err
	}
	defer f.Close()
	return suiteTmpl.Execute(f, view)
}

// emittedActionSubpaths returns the actions/<name> subpath strings that
// ActionEmitter would write for the given (spec, overlay) pair, sorted
// for deterministic emission. Filter mirrors ActionEmitter.Emit so the
// two stay in lock-step without sharing state.
func emittedActionSubpaths(spec Spec, overlay Overlay) []string {
	var subpaths []string
	for _, op := range spec.Operations {
		o, ok := overlay.Operations[op.ID]
		if !ok {
			continue
		}
		subpaths = append(subpaths, "actions/"+resolveActionName(op, o))
	}
	sort.Strings(subpaths)
	return subpaths
}

type suiteView struct {
	Name        string
	Description string
	Actions     []string
}

var suiteTmpl = template.Must(template.New("suite").Funcs(template.FuncMap{
	"quote":      tomlQuote,
	"hostsBlock": tomlMultilineList,
}).Parse(suiteTemplate))

const suiteTemplate = `# Aileron suite manifest for {{.Name}}.
#
# Generated by aileron-codegen. Lists every action emitted for this
# connector so ` + "`aileron action add-suite`" + ` installs the full
# surface in one shot. Re-run ` + "`task generate`" + ` after adding or
# removing operations from gen.yaml.

name = {{quote .Name}}
description = {{quote .Description}}

actions = {{hostsBlock .Actions}}
`
