package codegen

import (
	"bytes"
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"text/template"
)

// TransportEmitter renders connector/graphql.go — the GraphQL POST
// envelope wrapper, response parser, and the *graphqlErrors error
// type that DispatchEmitter's classify() inspects. Templated against
// the overlay's connector.endpoint URL and credential.kind.
//
// No-op when overlay.Connector.Endpoint is empty (transport URL is
// load-bearing; without it the emitted file would compile but the
// connector would dial the wrong host).
type TransportEmitter struct{}

func (TransportEmitter) Emit(spec Spec, overlay Overlay, outDir string) error {
	if overlay.Connector.Endpoint == "" {
		return nil
	}
	if len(emittableGraphQLOps(spec, overlay)) == 0 {
		return nil
	}
	view := transportView{
		Endpoint:       overlay.Connector.Endpoint,
		CredentialKind: overlay.Connector.Credential.Kind,
	}
	if view.CredentialKind == "" {
		// Defensive default; manifest emission errors much louder if
		// the overlay is missing the credential block.
		view.CredentialKind = "api_key"
	}
	var raw bytes.Buffer
	if err := transportTmpl.Execute(&raw, view); err != nil {
		return err
	}
	formatted, err := format.Source(raw.Bytes())
	if err != nil {
		return fmt.Errorf("gofmt generated graphql.go: %w", err)
	}
	dir := filepath.Join(outDir, "connector")
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return err
	}
	return os.WriteFile(filepath.Join(dir, "graphql.go"), formatted, 0o644)
}

type transportView struct {
	Endpoint       string
	CredentialKind string
}

var transportTmpl = template.Must(template.New("transport").Parse(transportTemplate))

const transportTemplate = `// Generated by aileron-codegen — do not edit.
//
// Re-run ` + "`task generate`" + ` to refresh after changing the spec or
// gen.yaml.

package main

import (
	"encoding/json"
	"fmt"
	"strings"
)

// graphqlEndpoint is the only outbound URL this connector dials. It
// must also appear in connector/manifest.toml's [capabilities.network].
const graphqlEndpoint = {{printf "%q" .Endpoint}}

// graphqlPayload is the JSON shape POSTed to graphqlEndpoint.
type graphqlPayload struct {
	Query     string         ` + "`json:\"query\"`" + `
	Variables map[string]any ` + "`json:\"variables,omitempty\"`" + `
}

// graphqlResponse is the JSON shape the upstream returns.
type graphqlResponse struct {
	Data   map[string]any ` + "`json:\"data,omitempty\"`" + `
	Errors []graphqlError ` + "`json:\"errors,omitempty\"`" + `
}

type graphqlError struct {
	Message string ` + "`json:\"message\"`" + `
	Path    []any  ` + "`json:\"path,omitempty\"`" + `
}

// graphqlErrors wraps a non-empty errors[] response so the dispatch
// layer can distinguish a GraphQL-level failure via errors.As(...).
type graphqlErrors struct {
	Errors []graphqlError
}

func (e *graphqlErrors) Error() string {
	msgs := make([]string, 0, len(e.Errors))
	for _, gqlErr := range e.Errors {
		msgs = append(msgs, gqlErr.Message)
	}
	return "graphql: " + strings.Join(msgs, "; ")
}

// graphqlCall builds the Aileron-host HTTP envelope, POSTs it via
// transport, and unmarshals the GraphQL response. Returns the parsed
// data map on success; returns a *graphqlErrors when the response
// carries non-empty errors[]; otherwise a transport/HTTP/parse error.
//
// The credential field tells the runtime to inject the bound
// credential header host-side per ADR-0005; the connector binary
// never holds the credential bytes.
func graphqlCall(transport Transport, query string, variables map[string]any) (map[string]any, error) {
	body, err := json.Marshal(graphqlPayload{Query: query, Variables: variables})
	if err != nil {
		return nil, fmt.Errorf("marshal graphql payload: %w", err)
	}
	req, err := json.Marshal(map[string]any{
		"method": "POST",
		"url":    graphqlEndpoint,
		"headers": map[string]string{
			"Accept":       "application/json",
			"Content-Type": "application/json",
		},
		"body":       string(body),
		"credential": {{printf "%q" .CredentialKind}},
	})
	if err != nil {
		return nil, fmt.Errorf("marshal http envelope: %w", err)
	}
	respBody, status, err := transport(req)
	if err != nil {
		return nil, fmt.Errorf("transport: %w", err)
	}
	if status < 200 || status >= 300 {
		return nil, fmt.Errorf("graphql HTTP %d: %s", status, truncate(string(respBody), 512))
	}
	var resp graphqlResponse
	if err := json.Unmarshal(respBody, &resp); err != nil {
		return nil, fmt.Errorf("parse graphql response: %w (body=%q)", err, truncate(string(respBody), 512))
	}
	if len(resp.Errors) > 0 {
		return nil, &graphqlErrors{Errors: resp.Errors}
	}
	return resp.Data, nil
}

func truncate(s string, max int) string {
	if len(s) <= max {
		return s
	}
	return s[:max] + "..."
}
`
