// Generated by aileron-codegen — do not edit.
//
// Re-run `task generate` to refresh after changing the spec or
// gen.yaml. Hand edits will be overwritten on the next run.

package main

import "fmt"

// Per-operation GraphQL constants and dispatch handlers.

const initiativeUpdateQuery = `query InitiativeUpdate($id: String!) {
  initiativeUpdate(id: $id) {
    body
    id
  }
}`

func handleInitiativeUpdate(args map[string]any, transport Transport) (map[string]any, error) {
	id, err := requireString(args, "id")
	if err != nil {
		return nil, err
	}
	variables := map[string]any{
		"id": id,
	}
	return graphqlCall(transport, initiativeUpdateQuery, variables)
}

const initiativeUpdateMutation = `mutation InitiativeUpdateMutation($input: InitiativeUpdateInput!) {
  initiativeUpdate(input: $input) {
    success
  }
}`

func handleInitiativeUpdateMutation(args map[string]any, transport Transport) (map[string]any, error) {
	body, err := requireString(args, "body")
	if err != nil {
		return nil, err
	}
	input := map[string]any{
		"body": body,
	}
	variables := map[string]any{
		"input": input,
	}
	return graphqlCall(transport, initiativeUpdateMutation, variables)
}

const viewerQuery = `query Viewer {
  viewer {
    id
    name
  }
}`

func handleViewer(args map[string]any, transport Transport) (map[string]any, error) {
	return graphqlCall(transport, viewerQuery, nil)
}

// Argument extraction helpers shared across all generated handlers.

func requireString(args map[string]any, name string) (string, error) {
	v, ok := args[name]
	if !ok {
		return "", fmt.Errorf("missing required arg %q", name)
	}
	s, ok := v.(string)
	if !ok {
		return "", fmt.Errorf("arg %q: expected string, got %T", name, v)
	}
	if s == "" {
		return "", fmt.Errorf("arg %q: must not be empty", name)
	}
	return s, nil
}

func requireInt(args map[string]any, name string) (int, error) {
	v, ok := args[name]
	if !ok {
		return 0, fmt.Errorf("missing required arg %q", name)
	}
	switch n := v.(type) {
	case int:
		return n, nil
	case float64:
		return int(n), nil
	}
	return 0, fmt.Errorf("arg %q: expected integer, got %T", name, v)
}

func requireFloat(args map[string]any, name string) (float64, error) {
	v, ok := args[name]
	if !ok {
		return 0, fmt.Errorf("missing required arg %q", name)
	}
	switch n := v.(type) {
	case float64:
		return n, nil
	case int:
		return float64(n), nil
	}
	return 0, fmt.Errorf("arg %q: expected number, got %T", name, v)
}

func requireBool(args map[string]any, name string) (bool, error) {
	v, ok := args[name]
	if !ok {
		return false, fmt.Errorf("missing required arg %q", name)
	}
	b, ok := v.(bool)
	if !ok {
		return false, fmt.Errorf("arg %q: expected bool, got %T", name, v)
	}
	return b, nil
}

func optionalString(args map[string]any, name string) (string, bool) {
	v, ok := args[name]
	if !ok || v == nil {
		return "", false
	}
	s, ok := v.(string)
	if !ok || s == "" {
		return "", false
	}
	return s, true
}

func optionalInt(args map[string]any, name string) (int, bool) {
	v, ok := args[name]
	if !ok || v == nil {
		return 0, false
	}
	switch n := v.(type) {
	case int:
		return n, true
	case float64:
		return int(n), true
	}
	return 0, false
}

func optionalFloat(args map[string]any, name string) (float64, bool) {
	v, ok := args[name]
	if !ok || v == nil {
		return 0, false
	}
	switch n := v.(type) {
	case float64:
		return n, true
	case int:
		return float64(n), true
	}
	return 0, false
}

func optionalBool(args map[string]any, name string) (bool, bool) {
	v, ok := args[name]
	if !ok || v == nil {
		return false, false
	}
	b, ok := v.(bool)
	return b, ok
}
